### ISSUE TITLE
List of possible technologies

### ISSUE THREAD

**Issue by WhiteCape1** [WhiteCape1/TeamProject#3]
Please post your ideas about the technologies to avoid duplicates

@SurajPS @mcsjuhasz @neerajaJoshy @franciscoandreso @TimEberts 

Thanks :+1:

**Comment by WhiteCape1** [comment]
- device detection by text labels within a switchboard

**Comment by franciscoandreso** [comment]
Augmented Reality app to show the features of a car to his owner

**Comment by mcsjuhasz** [comment]
My idea is based on this video: https://www.youtube.com/watch?v=9Wv9k_ssLcI&ab_channel=SAPEnterpriseMobile

At uni you guys know the PLC lab or the robotics lab. My idea is to develop a program for the glass which helps a person start/stop and monitor a system. For example: worker puts on the glasses in the beginning of his shift and via visual (augmented reality) and voice directions he is able to work with this system. (PLC or robots) We can place markers all around the area to highlight some important part of for example the safety system.

Something similar you can see in this video: https://www.youtube.com/watch?v=zppIGMDrwlE&ab_channel=OCOpenConsulting

**Comment by neerajaJoshy** [comment]
I found something similar to what Marcell has given. Check out this link below. It was developed recently by a startup in US. It uses data glasses/alternatives inbuilt with the safety helmet to be used in industries. It could be used for training of workers or for finding faults and repair work in the manufacturing industry. This is however a high end product. 

http://blog.grabcad.com/blog/2015/11/12/is-there-place-for-augmented-reality-in-manufacturing-yup/

Maybe we could focus on the repair part with real time information. For instance, right now when the AR display shows instructions to repair a device, you have to probably press next or show some gesture to go to next step. Instead we could use real time information by following the movement of our hand to automatically show the next step. I am not sure if that is already implemented. Please let me know if you guys find something on it. Meanwhile if I come across a different technology I will post it here.

**Comment by neerajaJoshy** [comment]
In addition to the above, to make it more realistic and practical for us to implement in this short period, I think we could maybe do a prototype of this. 

For instance, consider a department in the manufacturing industry. Using AR, we can have all the data regarding that department (say no. of workers on duty, overtime hours, project deadlines, production status, etc) displayed on the data glass. This could be connected to the server too. This would be for the maintenance workforce. It can make things more transparent and easy. 

In addition, we can also implement one for the production workforce. It could be for repair work/training as described earlier or something like safety related as Marcell suggested. Earlier I described about real time information while repair work. We can also have something which alarms the worker if he/she follows a wrong path. This can improve the efficiency.

**Comment by buergy** [comment]
my quick input: there are some solutions already in place, they all lack the AR part, though. See e.g. here:
http://www.entervise.com/
http://www.westunitis.co.jp/en/#Infolinker   (RMS software)
http://www.beeware.de/sodalis/    (sorry, only German)

Fraunhofer already included AR in tele maintenance, but it still be interesting for your "customer" to see if this is possible on recent devices, such as Epson or Vuzix:
http://tinyurl.com/jtth8k3

**Comment by SurajPS** [comment]
My idea is based on Alarm and event generation in industrial process automation. It is to generate alarm and event  on the display and then use hand gestures to View/Cancel the generated Alarm/Event in the industry. Additional Functionalities are performed using the Hand gestures.

**Comment by TimEberts** [comment]
Hallo I think of a speech controlled menu.
I think that would be a nice feature to combine with the others we implement. 
e.g.: we recognize an object or a label and highlight the one in the center. Then we can get more informations using our voice.
