### ISSUE TITLE
GitHub introduction

### ISSUE THREAD

**Issue by WhiteCape1** [WhiteCape1/TeamProject#4]
Hey guys,

I would like to know if you want me to give you a small introduction about GitHub next time. To show functionalities and possibilities.

Cheers!

**Comment by WhiteCape1** [comment]
Additional remark: I don't know why, but GitHub blocked my initial account from the h-da Email address. I sent a request to the technical service, but it might take a few days until they will answer and reactivate the account. To give you access to the meeting minutes and to enable a collaboration on GitHub, I opened a repository with another account of mine.
I will later transfer the repository to this reactivated h-da account (you probably won't even notice), which will then show my real name in the GitHub- username.

**Comment by mcsjuhasz** [comment]
Hey Thomas,
good idea, in the meantime would be nice if everybody can check out this site to get a basic principle and you can add your experience with this tool next time. :)

https://guides.github.com/activities/hello-world/

Cheers
