### ISSUE TITLE
Room for team meeting on Wed., Apr. 20th: D16/202

### ISSUE THREAD

**Issue by buergy** [WhiteCape1/TeamProject#6]
we'll meet in D16/202, I can unlock the room and let you in to return later.

Chr. Buergy

**Comment by TimEberts** [comment]
Hallo,

wenn ich mich nicht irre, hatten Sie gesagt, dass Sie uns ein paar Unity 
Beispiele geben könnten.
Könnten Sie mir diese bitte per Mail zukommen lassen?

Vielen Dank!

Mit freundlichen Grüßen
Tim Eberts

**Comment by buergy** [comment]
Hallo Herr Eberts,

anbei 3 Scripts im ZIP, Sie müssten diese als C#-Script den einzelnen Elementen zuordnen, z.B. einer 3D-Figur (rotatingMinion oder changeLight) oder einem TextFeld auf einem Canvas (TextEventHandler).

- rotating zeigt ein paar Tasten-Operationen und wie sich Objekte verschieben und drehen lassen
- changeLight ändert die Farbe der Lichtquelle und indirekt des Objekts
- Der TextEventHandler implementiert die Reaktionen auf erkannte Worte, die Sie mit dem Text prefab festlegen (dort müssen Sie eine WhiteListe anlegen mit den neuen zu erkennenden Worten).

Ich hoffe, das hilft mal für den Anfang...

Grüße
Chr. Bürgy

[UnityScripts.zip](https://github.com/WhiteCape1/TeamProject/files/239222/UnityScripts.zip)
